version: "3.8"
services:
  microfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prog8850-finalassignment-microfrontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: prog8850-finalassignment-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
